### ISSUE TITLE
All <HTML> tags should specify a language code

### ISSUE THREAD

**Issue by bedmison** [OpenDSA/OpenDSA#618]
Most of the <html> tags don't specify a language code. They should all have lang=en added to them so that the tag then looks like:

`<html lang="en">`

**Comment by bedmison** [comment]
These are fixed across all OpenDSA content in branch be.accessibility_updates_202409

**Comment by bedmison** [comment]
Turns out this is a breaking change, per Alex. Need to figure out why.

**Comment by bedmison** [comment]
Should support the book language.

**Comment by bedmison** [comment]
Assigned YoonWoo

**Comment by cashaffer** [comment]
"Should support the book language." means that the config file lets the user select a language. When possible, the module (and its contained exercises) will come from that language. But "en" is the default if there is none (which often there are not). So... ideally we would tag the module HTML with the appropriate language (what is actually compiled in, which might or might not be what is actually requested). In the case of the iframed exercises, etc, they ought to already carry their own html tag... except that the language can easily be switched (even on-the-fly) because it is a matter of pulling the associated strings from the JSON file for certain types of exercises.

**Comment by yoonwoo1000** [comment]
These are the list of files with this issue, that I found during the investigation.

Error occurs in HTML files in the Exercises/SWDesignAndDataStructs directory that does not have Summ in their names (ex: ArrayCheckpoint1Q2.html, BSTCheckpoint4Q1.html)

answer-types.js:1477 Uncaught TypeError: KhanUtil.shuffle is not a function
    at Object.setup (answer-types.js:1477:30)
    at makeProblem (khan-exercise.js:1321:47)
    at khan-exercise.js:2300:9
    at jquery.js:1192:33
    at fire (jquery.js:1037:30)
    at Object.add [as done] (jquery.js:1083:7)
    at Array.<anonymous> (jquery.js:1191:28)
    at Function.each (jquery.js:648:23)
    at Object.<anonymous> (jquery.js:1187:14)
    at Function.Deferred (jquery.js:1248:9)

The above error occurred in the RecMCQdepth.html, RecMCQinf.html, RecMCQinfresult.html, and RecMCQproof.html files in the Exercises/RecurTutor directory. 

I think it's a problem with data-require in HTML tags. It worked without error when I added the data-require="math" tag to ArrayCheckpoint1Q1.html in the SWDesignAndDataStructs directory.
There was an error in the RecurTutor directory, and the HTML tag of RecMCQdepth.html was data-require="spin". When I changed it to data-require="math spin", it worked without error.

**Comment by cashaffer** [comment]
I am confused about when you find an error. Do you mean that these exercises have an error before you made any change (adding the language to the HTML tag)? Or are you saying that these errors get generated once you add that tag?

**Comment by yoonwoo1000** [comment]
I did not change those files.

For Exercises/SWDesignAndDataStructs/ArrayCheckpoint1Q1.html, it already had lang="en", but it broke like the image below.

<img width="1274" alt="Image" src="https://github.com/user-attachments/assets/73fbba5e-473f-4578-9ab9-1bbb4e8c3347" />

Then, I added data-require="math" to the HTML, and the screen changed as shown below.

<img width="1130" alt="Image" src="https://github.com/user-attachments/assets/93b359ef-d4d8-4cc5-bc84-6c4e09c6f3ea" />


For Exercises/RecurTutor/RecMCQdepth.html, it did not have lang="en". Whether I modified it or not, the screen remained the same as shown below.

<img width="1129" alt="Image" src="https://github.com/user-attachments/assets/dc412be2-fbd6-4a38-b30c-0e4b84dbf411" />

I then changed data-require="spin" to data-require="math spin" in that file, and the screen changed as shown in the image below.


<img width="1127" alt="Image" src="https://github.com/user-attachments/assets/30977262-d4d1-46ba-9fbe-cd5266722640" />

**Comment by cashaffer** [comment]
Thanks for the details! I think what really matters is that they display properly when invoked from their summary exercise file. But it probably does not hurt to have them work correctly on their own. So when you see how to fix them, as you did with these two, please go ahead.

**Comment by cashaffer** [comment]
Are these changes committed and is this issue completed?
